Add: Flag to inject account id into sa annotation
giantswarm/amazon-eks-pod-identity-webhook pull request #2
Opened 2023-01-12 15:53 UTC by zewolfe

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-01-26 09:15 UTC, calvix approved these changes

2023-01-26 10:19 UTC, mnitchev requested changes

2023-01-26 10:19 UTC, mnitchev commented on pkg/cache/cache_test.go
> +	cache.(*serviceAccountCache).hasSynced = func() bool { return true }
this is bad practice. We should only be testing the returned Interface and not care about implementation details.

2023-01-26 10:19 UTC, mnitchev commented on pkg/cache/cache_test.go
> +	cache.(*serviceAccountCache).hasSynced = func() bool { return true }
As per [this example](https://github.com/kubernetes/client-go/blob/master/examples/fake-client/main_test.go) changing the `hasSynced` function shouldn't be necessary

2023-01-26 10:19 UTC, mnitchev commented on pkg/cache/cache_test.go
> +	roleArn, _, _, _ := cache.Get("default", "default")
This section can be written as:
```suggestion
	stop := make(chan struct{})
	informerFactory.Start(stop)
	cache.Start(stop)
	defer close(stop)

	var roleArn string
	err := wait.ExponentialBackoff(wait.Backoff{Duration: 10 * time.Millisecond, Factor: 1.0, Steps: 3}, func() (bool, error) {
		roleArn, _, _, _ = cache.Get("default", "default")
		return roleArn != "", nil
	})
	if err != nil {
		t.Fatalf("cache never returned role arn %v", err)
	}

```

2023-01-26 10:19 UTC, mnitchev commented on pkg/cache/cache.go
> +		klog.Errorf("Error getting instance identity document: %v", err.Error())
If there's an error here, then we just log the error, but the `indentity` will be empty. Are we alright with initializing with an empty identity? The previous code is erroring when getting the identity, so if we want to move to getting it only once, we should do that in `main`

2023-01-27 11:52 UTC, zewolfe commented on pkg/cache/cache.go
> +		klog.Errorf("Error getting instance identity document: %v", err.Error())
Good shout 👊🏾

2023-01-27 11:53 UTC, zewolfe commented on pkg/cache/cache_test.go
> +	cache.(*serviceAccountCache).hasSynced = func() bool { return true }
Thanks 😄

2023-01-27 13:11 UTC, mnitchev commented on pkg/cache/fake.go
> +	v1 "k8s.io/api/core/v1"
Small nitpick but this should probably be moved in the above section. Otherwise it will probably fail `goimports --local` validation

2023-01-27 13:42 UTC, mnitchev approved these changes

2023-01-31 09:35 UTC, merged